name: covid19inc-env
dependencies:
    - python>=3.7
    - numpy>=1.16.4
    - pytest>=4.0.2
    - scikit-learn>=0.22.1
    - pandas
    - scipy
    - matplotlib
    - seaborn
    - jupyter
    - coverage
    # Pip dependencies
    - pip